In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
raw_data = pd.read_csv("./Datasets/Sharktankpitchesdeals.csv")

In [3]:
raw_data.head()

Season_Epi_code Pitched_Business_Identifier  \
0              826                Bridal Buddy   
1              826                  Laid Brand   
2              826                  Rocketbook   
3              826               Wine & Design   
4              824              Peoples Design   

                               Pitched_Business_Desc  Deal_Status Deal_Shark  
0  a functional slip worn under a wedding gown th...            1     KOL+LG  
1  hair-care products made with pheromones . Laid...            0        NaN  
2  a notebook that can scan contents to cloud ser...            0        NaN  
3  painting classes with wine served . Wine & Des...            1        KOL  
4  a mixing bowl with a built-in scoop . Peoples ...            1         LG

In [4]:
new_raw_data = pd.DataFrame()

In [5]:
new_raw_data['Pitched_Business_Description'] = raw_data['Pitched_Business_Desc']

In [6]:
new_raw_data['Deal_cracked_or_not'] = raw_data['Deal_Status']

In [7]:
new_raw_data.head()

Pitched_Business_Description  Deal_cracked_or_not
0  a functional slip worn under a wedding gown th...                    1
1  hair-care products made with pheromones . Laid...                    0
2  a notebook that can scan contents to cloud ser...                    0
3  painting classes with wine served . Wine & Des...                    1
4  a mixing bowl with a built-in scoop . Peoples ...                    1

In [8]:
updated_pitched_business_desc = new_raw_data['Pitched_Business_Description'].apply(lambda x: re.sub("[^a-zA-Z]"," ",x).lower())

In [9]:
new_raw_data['Pitched_Business_Description'] = updated_pitched_business_desc

In [10]:
new_raw_data.head()

Pitched_Business_Description  Deal_cracked_or_not
0  a functional slip worn under a wedding gown th...                    1
1  hair care products made with pheromones   laid...                    0
2  a notebook that can scan contents to cloud ser...                    0
3  painting classes with wine served   wine   des...                    1
4  a mixing bowl with a built in scoop   peoples ...                    1

In [11]:
new_raw_data.shape

(706, 2)

In [12]:
def set_of_words(desc):
    
    desc_list = desc.split(sep=" ")
    
    desc_set = set(desc_list)
    
    return desc_set

In [13]:
bag_of_words = new_raw_data['Pitched_Business_Description'].apply(lambda x: set_of_words(x))

In [14]:
bag_of_words[0]

{'',
 'a',
 'allows',
 'bag',
 'bathroom',
 'bridal',
 'bride',
 'brides',
 'buddy',
 'bustle',
 'calls',
 'can',
 'functional',
 'go',
 'gown',
 'her',
 'herself',
 'is',
 'it',
 'lets',
 'lightweight',
 'making',
 'mess',
 'nature',
 'on',
 'own',
 'relieve',
 'restroom',
 'safely',
 'slip',
 'that',
 'the',
 'their',
 'to',
 'under',
 'up',
 'use',
 'wearer',
 'wearing',
 'wedding',
 'when',
 'while',
 'without',
 'worn'}

In [15]:
unique_bag_of_words = set()

In [16]:
total_words = 0

In [17]:
for i in range(0,706):
    
    unique_bag_of_words = unique_bag_of_words.union(bag_of_words[i])
    
    total_words += len(bag_of_words)

In [18]:
new_raw_data['Pitched_Business_Description'] = bag_of_words

In [19]:
new_raw_data.head()

Pitched_Business_Description  Deal_cracked_or_not
0  {, is, gown, the, use, restroom, go, worn, whi...                    1
1  {, is, goes, the, and, help, color, that, prod...                    0
2  {, is, erased, the, use, smartphone, and, scan...                    0
3  {, design, and, space, artist, each, where, lo...                    1
4  {, is, kitchen, the, and, space, various, remo...                    1

In [20]:
pos_class_data = new_raw_data[new_raw_data['Deal_cracked_or_not'] == 1]

In [21]:
neg_class_data = new_raw_data[new_raw_data['Deal_cracked_or_not'] == 0]

In [22]:
pos_class_training_data = pos_class_data.iloc[0:int(0.75*len(new_raw_data))//2]

In [23]:
neg_class_training_data = neg_class_data.iloc[0:int(0.75*len(new_raw_data))//2]

In [24]:
training_data = pd.concat([pos_class_training_data,neg_class_training_data])

In [25]:
pos_class_testing_data = pos_class_data.iloc[int(0.75*len(new_raw_data))//2:]

In [26]:
neg_class_testing_data = neg_class_data.iloc[int(0.75*len(new_raw_data))//2:]

In [27]:
testing_data = pd.concat([pos_class_testing_data,neg_class_testing_data])

In [28]:
training_data.shape

(528, 2)

In [29]:
unique_bag_of_words

{'',
 'sorority',
 'calms',
 'protects',
 'designers',
 'yuk',
 'degrees',
 'hoodie',
 'hollow',
 'to',
 'bed',
 'handsfree',
 'themed',
 'tracks',
 'gadgets',
 'feeder',
 'masks',
 'strength',
 'setup',
 'designer',
 'algae',
 'convert',
 'recycled',
 'quicker',
 'decadent',
 'entire',
 'size',
 'olive',
 'weatherproof',
 'rareform',
 'shelving',
 'veterinarian',
 'leds',
 'calm',
 'minutes',
 'changing',
 'turn',
 'bait',
 'extension',
 'techniques',
 'lollacup',
 'extracts',
 'mustaches',
 'belief',
 'stuffed',
 'gear',
 'read',
 'tattoo',
 'razor',
 'concentrated',
 'acts',
 'able',
 'sunscreenr',
 'smoothie',
 'nighttime',
 'revive',
 'professional',
 'champion',
 'petplate',
 'shots',
 'sending',
 'doesn',
 'headbands',
 'away',
 'space',
 'bliss',
 'storage',
 'puts',
 'page',
 'bolts',
 'digitally',
 'posters',
 'dressing',
 'inchbug',
 'cleanwrap',
 'recumbent',
 'breast',
 'dress',
 'creaproducts',
 'freeing',
 'measured',
 'came',
 'pop',
 'hands',
 'validated',
 'insert',
 

In [30]:
def frequency_determination(desc):
    
    one_hot_encoded_list = []

    for unique_words in list(unique_bag_of_words):
        
        one_hot_encoded_list.append(unique_words in desc)

    return one_hot_encoded_list

In [31]:
one_hot_encoded_vectors_pos = []

one_hot_encoded_vectors_pos.extend(map(lambda x: frequency_determination(x),pos_class_training_data.iloc[:,0]))

In [32]:
one_hot_encoded_vectors_pos = np.array(one_hot_encoded_vectors_pos)

In [33]:
cracked_deal_word_frequencies = np.sum(one_hot_encoded_vectors_pos,axis=0)

In [34]:
cracked_deal_word_relative_frequencies = cracked_deal_word_frequencies/pos_class_training_data.shape[0]

In [35]:
cracked_deal_word_relative_frequencies += (1/(pos_class_training_data.shape[0]+len(unique_bag_of_words)))*(cracked_deal_word_relative_frequencies == 0)

In [36]:
D_cracked_deal = dict(zip(list(unique_bag_of_words),list(cracked_deal_word_relative_frequencies)))

In [37]:
D_cracked_deal

{'': 1.0,
 'sorority': 0.003787878787878788,
 'calms': 0.003787878787878788,
 'protects': 0.003787878787878788,
 'designers': 0.003787878787878788,
 'yuk': 0.00021181952976064393,
 'degrees': 0.003787878787878788,
 'hoodie': 0.00021181952976064393,
 'hollow': 0.00021181952976064393,
 'to': 0.5757575757575758,
 'bed': 0.00021181952976064393,
 'handsfree': 0.003787878787878788,
 'themed': 0.011363636363636364,
 'tracks': 0.007575757575757576,
 'gadgets': 0.003787878787878788,
 'feeder': 0.00021181952976064393,
 'masks': 0.00021181952976064393,
 'strength': 0.007575757575757576,
 'setup': 0.00021181952976064393,
 'designer': 0.011363636363636364,
 'algae': 0.00021181952976064393,
 'convert': 0.003787878787878788,
 'recycled': 0.01893939393939394,
 'quicker': 0.007575757575757576,
 'decadent': 0.00021181952976064393,
 'entire': 0.003787878787878788,
 'size': 0.003787878787878788,
 'olive': 0.00021181952976064393,
 'weatherproof': 0.003787878787878788,
 'rareform': 0.003787878787878788,
 's

In [38]:
one_hot_encoded_vectors_neg = []

one_hot_encoded_vectors_neg.extend(map(lambda x: frequency_determination(x),neg_class_training_data.iloc[:,0]))

In [39]:
one_hot_encoded_vectors_neg = np.array(one_hot_encoded_vectors_neg)

In [40]:
not_cracked_deal_word_frequencies = np.sum(one_hot_encoded_vectors_neg,axis=0)

In [41]:
not_cracked_deal_word_relative_frequencies = not_cracked_deal_word_frequencies/neg_class_training_data.shape[0]

In [42]:
not_cracked_deal_word_relative_frequencies

array([1.        , 0.        , 0.        , ..., 0.00378788, 0.00378788,
       0.        ])

In [43]:
not_cracked_deal_word_relative_frequencies += (1/(neg_class_training_data.shape[0]+len(unique_bag_of_words)))*(not_cracked_deal_word_relative_frequencies == 0)

In [44]:
D_not_cracked_deal = dict(zip(list(unique_bag_of_words),list(not_cracked_deal_word_relative_frequencies)))

In [45]:
D_not_cracked_deal

{'': 1.0,
 'sorority': 0.00021181952976064393,
 'calms': 0.00021181952976064393,
 'protects': 0.003787878787878788,
 'designers': 0.00021181952976064393,
 'yuk': 0.003787878787878788,
 'degrees': 0.00021181952976064393,
 'hoodie': 0.00021181952976064393,
 'hollow': 0.003787878787878788,
 'to': 0.4166666666666667,
 'bed': 0.011363636363636364,
 'handsfree': 0.00021181952976064393,
 'themed': 0.003787878787878788,
 'tracks': 0.00021181952976064393,
 'gadgets': 0.00021181952976064393,
 'feeder': 0.003787878787878788,
 'masks': 0.003787878787878788,
 'strength': 0.00021181952976064393,
 'setup': 0.003787878787878788,
 'designer': 0.003787878787878788,
 'algae': 0.003787878787878788,
 'convert': 0.00021181952976064393,
 'recycled': 0.003787878787878788,
 'quicker': 0.00021181952976064393,
 'decadent': 0.00021181952976064393,
 'entire': 0.007575757575757576,
 'size': 0.003787878787878788,
 'olive': 0.003787878787878788,
 'weatherproof': 0.00021181952976064393,
 'rareform': 0.0002118195297606

In [46]:
def calculate_likeli_probability(word_relative_frequencies,data):

    likeli_prob = []

    for word in list(data):
    
        likeli_prob.append(word_relative_frequencies[word])
        
    return np.prod(np.array(likeli_prob))

In [47]:
likeli_probabilities_cracked = []

likeli_probabilities_cracked.extend(map(lambda x,y: calculate_likeli_probability(x,y),[D_cracked_deal]*len(testing_data),testing_data.iloc[:,0]))

In [48]:
likeli_probabilities_cracked = np.array(likeli_probabilities_cracked)

In [49]:
likeli_probabilities_not_cracked = []

likeli_probabilities_not_cracked.extend(map(lambda x,y: calculate_likeli_probability(x,y),[D_not_cracked_deal]*len(testing_data),testing_data.iloc[:,0]))

In [50]:
likeli_probabilities_not_cracked = np.array(likeli_probabilities_not_cracked)

In [51]:
posterior_cracked = likeli_probabilities_cracked/(likeli_probabilities_cracked + likeli_probabilities_not_cracked)

In [52]:
posterior_cracked

array([1.00000000e+00, 9.99996792e-01, 6.45533919e-02, 1.66666667e-01,
       1.00000000e+00, 7.77777778e-01, 9.99824446e-01, 9.99997820e-01,
       9.99660332e-01, 9.99583229e-01, 9.94277671e-01, 1.11423379e-04,
       1.16218730e-01, 5.00000000e-01, 9.41182738e-01, 9.94836270e-01,
       9.99885769e-01, 9.99999880e-01, 9.99980172e-01, 9.10235487e-01,
       9.96671378e-01, 9.98734594e-01, 6.23030650e-01, 4.66873002e-03,
       8.91891892e-01, 7.43852459e-01, 9.99686729e-01, 9.72800330e-01,
       9.92003696e-01, 9.98685642e-01, 1.73349676e-01, 8.54037267e-01,
       1.00000000e+00, 2.58823529e-01, 2.95774648e-01, 9.20530703e-01,
       3.33333333e-01, 5.79478788e-02, 9.99895519e-01, 9.98498063e-01,
       1.18683286e-01, 9.97204947e-01, 2.85714286e-01, 9.99999835e-01,
       1.04127668e-03, 6.38778220e-01, 9.94305702e-01, 1.46631861e-02,
       5.71428571e-01, 9.98696733e-01, 5.35211268e-01, 9.79460581e-01,
       1.00000000e+00, 9.65877715e-02, 8.69565217e-01, 6.30344630e-01,
      

In [53]:
predicted_classes = np.uint8(posterior_cracked > 0.5)

In [54]:
predicted_classes

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0], dtype=uint8)

In [55]:
actual_classes = np.array(testing_data.iloc[:,1])

In [56]:
actual_classes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [57]:
correct_count_test = np.count_nonzero(np.equal(predicted_classes,actual_classes))

In [58]:
correct_count_test

112

In [59]:
accuracy_test = (correct_count_test/actual_classes.shape[0])*100

In [61]:
accuracy_test

62.92134831460674

In [62]:
likeli_probabilities_cracked_train = []

likeli_probabilities_cracked_train.extend(map(lambda x,y: calculate_likeli_probability(x,y),[D_cracked_deal]*len(training_data),training_data.iloc[:,0]))

In [63]:
likeli_probabilities_not_cracked_train = []

likeli_probabilities_not_cracked_train.extend(map(lambda x,y: calculate_likeli_probability(x,y),[D_not_cracked_deal]*len(training_data),training_data.iloc[:,0]))

In [64]:
likeli_probabilities_cracked_train = np.array(likeli_probabilities_cracked_train)

In [65]:
likeli_probabilities_not_cracked_train = np.array(likeli_probabilities_not_cracked_train)

In [66]:
posterior_cracked_train = likeli_probabilities_cracked_train/(likeli_probabilities_cracked_train + likeli_probabilities_not_cracked_train)

In [73]:
predicted_classes_train = np.uint8(posterior_cracked_train > 0.5)

In [74]:
predicted_classes_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [69]:
actual_classes_train = np.array(training_data.iloc[:,1])

In [70]:
actual_classes_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [75]:
correct_count_train = np.count_nonzero(np.equal(predicted_classes_train,actual_classes_train))

In [76]:
correct_count_train

513

In [79]:
accuracy_train = (correct_count_train/training_data.shape[0])*100

In [80]:
accuracy_train

97.1590909090909